### ISSUE TITLE
Como instalar ocaml-lsp

### ISSUE THREAD

**Issue by enieber** [rescriptbr/comece-aqui#13]
Já estou escrevendo alguns codigos em reason/ocaml a algum tempo, porem ainda não consegui rodar o ocaml-lsp junto com o vs-code ou vim, alguém tem alguma sugestão de tutorial de como fazer isso?

**Comment by fakenickels** [comment]
O melhor é instalar usando o esy e depois ativar pro VSCode Platform usar o ocaml-lsp do sandbox do esy com ctrl+shift+p
