### ISSUE TITLE
Dicionario tecnico

### ISSUE THREAD

**Issue by enieber** [rescriptbr/comece-aqui#15]
Quando se ta estudando rescript, é muito comum acabar encontrando palavras chaves como:

 - reasonml
 - OCaml
 - BucleScript
 - imutabilidade
 - esy
 - dune
 - binding

Seria muito legal se tivesse um dicionario tecnico explicando esses termos apesar do rescript não depender da maioria desses termos.

**Comment by vmarcosp** [comment]
Eu removeria alguns dos termos, mas acho muito boa a ideia! Se quiser tocar isso =)
