### ISSUE TITLE
Atualização no guia de bindings

### ISSUE THREAD

**Issue by zoedsoupe** [rescriptbr/comece-aqui#16]
Sou novo na comunidade e logo encontrei o guia do [yawaramin](https://github.com/yawaramin/bucklescript-bindings-cookbook/blob/master/ReScript.md).

Porém, ele está desatualizado com a nova sintaxe de =ReScript= e também não é muito explcíto nos exemplos, por isso, decidi refazê-lo, com a nova sintaxe e uma nova estrutura.

pode ser acessado aqui: https://github.com/matdsoupe/rescript-bindings-cookbook

**Comment by zoedsoupe** [comment]
talvez seja interessante traduzir para pt-br?

**Comment by vmarcosp** [comment]
Fala @matdsoupe, boa iniciativa!

Eu já havia falado com yawarmin sobre uma atualização e ele me informou que já tinha um arquivo MD que estava atualizado com a nova sintaxe. No entanto acho interessante termos uma versão mais completa e até mesmo em pt-br. O que acha de mover esse seu cookbook para o rescriptbr? Assim podemos contribuir e fazer juntos :)

**Comment by zoedsoupe** [comment]
Concordo! Falei com ele tbm, nesta issue: https://github.com/yawaramin/bucklescript-bindings-cookbook/issues/1#issuecomment-907542116

Posso passar pra organização sim!

**Comment by vmarcosp** [comment]
Legal, assim que puder te adicionou aqui na org também, bora construir isso aí juntos :)

**Comment by zoedsoupe** [comment]
perfeito! (:

**Comment by vmarcosp** [comment]
@matdsoupe te adicionei na org.

Estava pensando sobre esse cookbook no final de semana e acho que o projeto tem bastante potencial. Poderíamos criar um cheatsheet bem completo utilizando docusaurus e publicar no netlify. Eu posso criar um branding e uma landing page  e aí criamo uma estrutura legal para os exemplos, o que acha? Ter um site / doc vai ser legal para indexação e também para ter uma UX mais rica, podemos implementar um sistema de busca usando algolia também. Vai ser um complemento legal para a doc. oficial.

**Comment by zoedsoupe** [comment]
boa! gostaria bastante de fazer parte disso!

concordo, com um website fica mais fácil de mostrar os exemoplos e temos mais possibilidade de brincarmos com a usabilidade tbm!

**Comment by vmarcosp** [comment]
legal, se quiser começar iniciar a criação do setup com o docusaurus, bem simples mesmo, só seguindo a doc deles... depois eu crio um branding e uma landing page e fazemos ele dentro do docusaurus usando rescript.

**Comment by vmarcosp** [comment]
@matdsoupe segue o guia da doc e cria usando o tema classic, é mais fácil simples de customizar.
Link ➡️ https://docusaurus.io/docs/api/themes/@docusaurus/theme-classic

**Comment by zoedsoupe** [comment]
beleza! vou tentar arranjar um tempinho livre, se não nesse semana, pelo menos no fim de semana.
