### ISSUE TITLE
Qual a diferença entre -> e |>

### ISSUE THREAD

**Issue by enieber** [rescriptbr/comece-aqui#8]
Recentemente fiz esse codigo usando Serbet, porem não consegui entende por que não posso colocar |> para tudo?

```ocaml
open Async;
open Serbet.Endpoint;

[@decco]
type body_out = {message: string};

let endpoint =
  Serbet.endpoint({
    verb: GET,
    path: "/",
    handler: (_req) => {
      let response = {message: "Bom dia" }
      response 
        -> body_out_encode
        -> OkJson 
        |> async;
    },
  });
```

**Comment by fakenickels** [comment]
a diferença é que o `->` envia o argumento pro primeiro param da função e o `|>` pro último o `->` na real é uma sintaxe do BuckleScript já o `|>` é uma função.

```reason
let (|>): ('a, 'a => 'b) => 'b;
```

```
Reverse-application operator: x |> f |> g is exactly equivalent to g (f (x)).
Since 4.01
```
saca ele realmente é uma função!
o `->` foi introduzido pelo BS pq geralmente o custo dele é menor em JS e os erros de tipo tb geralmente ficam melhores com ele.

Outra diferença notável:

```reason
response 
        -> body_out_encode
        -> OkJson 
        |> async;
```

vc pode fazer `-> OkJson` usar ele contra uma variante pq ele é uma sintaxe
mas vc não pode fazer `|> OkJson` pq `|>` é uma função e aquilo não faz sentido na linguagem
